# Generated by Django 5.0.6 on 2024-06-05 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Url',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=6)),
                ('long_url', models.URLField()),
                ('short_url', models.URLField()),
            ],
        ),
    ]
