# Generated by Django 5.0.6 on 2024-06-05 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shortener_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='url',
            name='long_url',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='url',
            name='short_url',
            field=models.CharField(max_length=50),
        ),
    ]
